# Generated by Django 4.2.7 on 2023-11-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('reg_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('year_of_make', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('services', models.TextField()),
                ('lifejacket', models.BooleanField()),
                ('fire_extinguisher', models.BooleanField()),
                ('location', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('active_status', models.BooleanField()),
            ],
        ),
    ]
