# Generated by Django 4.2.7 on 2023-11-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='fire_extinguisher',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='lifejacket',
            field=models.IntegerField(),
        ),
    ]
