# Generated by Django 4.2.7 on 2023-11-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat_management', '0002_initial'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people_count', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=20)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_management.boat')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.customer')),
            ],
        ),
    ]
