# Generated by Django 4.2.7 on 2023-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_remove_customer_address_remove_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='license',
            field=models.CharField(default='1234', max_length=100, unique=True),
        ),
    ]
