# Generated by Django 4.2.7 on 2023-11-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_owner_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.customuser'),
        ),
    ]
