# Generated by Django 4.2.7 on 2023-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_alter_customuser_role_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='email',
            field=models.EmailField(default='lolol', max_length=254, unique=True),
        ),
    ]
